export type IConfig = {
	name?: string,
};

// export type IPage = {
// 	puid?: string,
// 	unique: string,
// 	stack: string,
// 	parent: string | null,
// 	initial?: boolean,
// 	path: string,
// 	title: string,
// 	titleAlt?: string,
// 	tab: string,
// 	meta: Record<string, any>,
// 	data: Record<string, any>,
// 	form: IForm,
// 	globals: IPageGlobals,
// 	parts: ReturnType<typeof getPathParts>,
// 	controls: ReturnType<typeof useControls>,
// 	dynamic: ReturnType<typeof useDynamic>,
// 	action: ActionHandler,
// };

// export type IForm = {
// 	type?: 'page' | 'modal' | 'sidebar',
// 	uid?: string,
// 	title: string,
// 	titleAlt: string,
// 	actions: IAction[],
// 	options?: IFormOptions,
// 	display?: IFormDisplay,
// 	controls: Record<string, IControl>,
// 	tabs: Record<string, ITab>,
// 	fields: Record<string, IField>,
// 	meta?: Record<string, any>,
// 	values?: Record<string, any>,
// 	watchers?: Record<string, IWatcher>,
// 	shortcuts?: Record<string, IAction[]>,
// };

// export type IField = {
// 	tab: string,
// 	component: string,
// 	group?: string,
// 	type?: string,
// 	meta?: string,
// 	unique: string,
// 	xpath: string,
// 	key: string,
// 	parent: string,
// 	zone?: string,
// 	fikso?: string,
// 	settings: IFieldSettings,
// 	fields?: Record<string, IField>,
// 	label?: string,
// 	validation: IFieldValidation,
// 	listeners?: string[],
// 	events: IFieldEvent[],
// 	options: IUseFieldOptions<Record<string, boolean>>,
// 	formatters: Record<string, IFormatterSchema>,
// 	override?: Record<string, any>,
// 	includePath?: boolean,
// };
